default_install_hook_types:
- pre-push

repos:
- repo: local
  hooks:
  - id: clean
    name: Clean
    entry: make
    args: [ "clean" ]
    language: system
    pass_filenames: false
    types: [ "c++", "c" ]
    files: ^(Logic/)|(Core/)|(BSP/)|(Middlewares/)|(Drivers/)|(scilla.ioc)
  - id: build
    name: Build
    entry: make
    args: [ "build" ]
    language: system
    pass_filenames: false
    types: [ "c++", "c" ]
    files: ^(Logic/)|(Core/)|(BSP/)|(Middlewares/)|(Drivers/)|(scilla.ioc)
  - id: check-formatting
    name: Check formatting
    entry: clang-format
    args: [ "--Werror", "--dry-run" ]
    language: "system"
    types: [ "c++", "c" ]
    pass_filenames: true
    files: ^(Logic/)
